name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true   # ✅ allow deprecated Node.js

jobs:

  build-test-analyze:
    runs-on: ubuntu-latest
    env:
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci --ignore-scripts

      - name: Run Jest tests with coverage
        run: npm test -- --coverage

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage/lcov.info
      
      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v5.0.0 # Or current stable SHA update
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.projectKey=md-sadidtahsin_assignment-14-final
            -Dsonar.organization=md-sadidtahsin
            -Dsonar.sources=src
            -Dsonar.exclusions=**/node_modules/**
            -Dsonar.test.inclusions=tests/**/*.test.js
            -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
            -Dsonar.qualitygate.wait=true

      
 